staticRoot: ../static/
secretFile: /opt/web-apps/dariah_jwt.secret
shibKey: Shib-Session-ID

# the next parameter may have values ajp, http, null
transportAttributes: http

creator: HaSProject

database:
  development: dariah_dev
  test: dariah_test
  production: dariah

root:
  dariah: DirkRoorda@dariah.eu
  dariah_dev: dirk
  dariah_test: root

debug:
  cache: false
  mongo: false
  auth: true

attributes:
  o: org
  cn: name
  givenName: firstName
  sn: lastName
  isMemberOf: membership
  affiliation: rel

objects:
  - context
  - db
  - wf
  - auth
  - types

names:
  - DARIAH
  - mail
  - ajp
