staticRoot: ../static/
secretFile: /opt/web-apps/dariah_jwt.secret
shibKey: Shib-Session-ID
creator: HaSProject

debug: false

attributes:
  o: org
  cn: name
  givenName: firstName
  sn: lastName
  isMemberOf: membership
  affiliation: rel

objects:
  - context
  - db
  - wf
  - auth
  - types

names:
  - DARIAH
  - devel
  - mail
  - REGIME
