fields:
  - assessment
  - assessmentType
  - contrib
  - country
  - creator
  - criteria
  - criteriaEntry
  - dateCreated
  - dateDecided
  - dateSubmitted
  - dateWithdrawn
  - decision
  - editors
  - evidence
  - review
  - reviewerE
  - reviewerF
  - reviewType
  - score
  - selected
  - submitted
  - title
  - typeContribution

workflowSubfields:
  - overall
  - relevantScore
  - relevantMax
  - relevantN
  - allMax
  - allN

stageAtts:
  selectNone:
    msg: No selection decision by National Coordinator
    cls: info
  selectYes:
    msg: Contribution has been accepted by National Coordinator
    cls: good
  selectNo:
    msg: Contribution has been rejected by National Coordinator
    cls: error
  submitted:
    msg: Assessment submitted
    cls: info
  submittedRevised:
    msg: Revised Assessment submitted
    cls: info
  complete:
    msg: Assessment complete
    cls: info
  completeRevised:
    msg: Revised assessment complete
    cls: info
  completeWithdrawn:
    msg: Withdrawn
    cls: error
  incomplete:
    msg: Assessment incomplete
    cls: warning
  incompleteRevised:
    msg: Revised assessment incomplete
    cls: warning
  incompleteWithdrawn:
    msg: Withdrawn
    cls: error
  reviewAdviseRevise:
    msg: "advice: Revise"
    cls: warning
  reviewAdviseAccept:
    msg: "advice: Accept"
    cls: good
  reviewAdviseReject:
    msg: "advice: Reject"
    cls: error
  reviewRevise:
    msg: Revision required
    cls: warning
  reviewAccept:
    msg: Accepted
    cls: good
  reviewReject:
    msg: Rejected
    cls: error

assessmentStages:
  - submitted
  - submittedRevised
  - complete
  - completeRevised
  - incomplete
  - incompleteRevised

statusRep:
  frozen: Finalized and frozen
  locked: Locked
  done: Finished

tasks:
  selectContrib:
    msg: Select as national contribution to DARIAH
    acro: select contribution
    cls: good
    operator: set
    table: contrib
    field: selected
    date: dateDecided
    delay: 96
    value: "1"
  deselectContrib:
    msg: Discard as national contribution to DARIAH
    acro: discard contribution
    cls: error
    operator: set
    table: contrib
    field: selected
    date: dateDecided
    delay: 96
    value: "-1"
  unselectContrib:
    msg: Revoke selection decision for this contribution
    acro: unselect contribution
    cls: warning
    operator: set
    table: contrib
    field: selected
    date: dateDecided
    delay:
      all: false
      coord: 96
      office: 2400
      sysadmin: true
    value: "0"
  startAssessment:
    msg: Start a self-assessment for this contribution
    acro: start assessment
    cls: info
    operator: add
    table: contrib
    detail: assessment
  submitAssessment:
    msg: Submit assessment
    acro: submit assessment
    cls: info
    operator: set
    table: assessment
    field: submitted
    date: dateSubmitted
    delay: 1
    value: "1"
  resubmitAssessment:
    msg: Resubmit assessment
    acro: resubmit assessment
    cls: info
    operator: set
    table: assessment
    field: submitted
    date: dateSubmitted
    delay: 1
    value: "1"
  submitRevised:
    msg: Submit revised assessment
    acro: resubmit revision
    cls: info
    operator: set
    table: assessment
    field: submitted
    date: dateSubmitted
    delay: 1
    value: "now"
  withdrawAssessment:
    msg: Withdraw assessment from review
    acro: withdraw assessment
    cls: error
    operator: set
    table: assessment
    field: submitted
    date: dateWithdrawn
    delay: 1
    value: "0"
  startReview:
    msg: Start a review of this assessment
    acro: start review
    cls: info
    operator: add
    table: assessment
    detail: review
  expertReviewRevise:
    kind: expert
    msg: Advise revision
    acro: advise revision
    cls: warning
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 2
    value: Revise
  expertReviewAccept:
    kind: expert
    msg: Advise to accept
    acro: advise accept
    cls: good
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 2
    value: Accept
  expertReviewReject:
    kind: expert
    msg: Advise to reject
    acro: advise reject
    cls: error
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 2
    value: Reject
  expertReviewRevoke:
    kind: expert
    msg: Revoke
    acro: revoke
    cls: warning
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 24
    value: null
  finalReviewRevise:
    kind: final
    msg: Require revision
    acro: require revision
    cls: warning
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 24
    value: Revise
  finalReviewAccept:
    kind: final
    msg: Accept
    acro: accept
    cls: good
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 24
    value: Accept
  finalReviewReject:
    kind: final
    msg: Reject
    acro: reject
    cls: error
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 24
    value: Reject
  finalReviewRevoke:
    kind: final
    msg: Revoke
    acro: revoke
    cls: warning
    operator: set
    table: review
    field: decision
    date: dateDecided
    delay: 24
    value: null

workflow:
  - complete
  - contribId
  - frozen
  - kind
  - reviewer
  - reviews
  - status
  - type

info:
  - _id
  - creators
  - contribId
  - frozen
  - kind
  - mayAdd
  - reviewer
  - reviewers
  - reviews
  - stage
  - stageDate
  - title
  - type

decisionDelay: 3600

names:
  - actual
  - expert
  - final
  - orphaned
  - taskFields
  - wfitem
